# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and build
on:
    - pull_request
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'

            - name: Install dependencies
              run: pnpm install

            - name: Build application
              run: pnpm build

            - name: Run tests
              run: pnpm run test:ci
